name: Docker CI New solicitudes

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Usamos 'lower' para evitar el error de mayúsculas en el nombre del dueño
          tags: |
            ghcr.io/${{ github.repository_owner }}/new-solicitudes:latest
          labels: |
            org.opencontainers.image.title=new-solicitudes-container